### ISSUE TITLE
Apple Silicon / darwin-arm64 / m1 Support

### ISSUE THREAD

**Issue by sammcj** [heyvito/podman-macos#3]
As noted in your readme it would be great to have Apple Silicon / M1 support.

I'd be happy to test it out if you have a build but not the hardware.

**Comment by simnalamburt** [comment]
Actually I’ve been talking about this issue at the #2.

### Discussed in https://github.com/heyvito/podman-macos/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **simnalamburt** September  5, 2021</sup>
Hi @heyvito! I have [patched and packaged qemu and podman](https://github.com/simnalamburt/homebrew-x/) to make it work with Apple Silicon, and now I'm looking for the way to integrate it with podman-macos.

This is how to use patched version of podman in the CLI:
```bash
brew install simnalamburt/x/podman-apple-silicon

# Example
podman machine init
podman machine start
podman run -p 8080:80 docker.io/nginx
```

I tried to use it with podman-macos and this is the issues I get:

1.  podman-macos do not search podman binary in `/opt/homebrew/bin`

    You can workaround this issue by `sudo ln -s /opt/homebrew/bin/podman /usr/local/bin/podman`, but it would be better if podman-macos checks the `/opt/homebrew/bin`. Maybe we can fix this by appending `/opt/homebrew/bin` at the end of the result of [`PMManager::paths`](https://github.com/heyvito/podman-macos/blob/7f3b8933d6eed5db438dfc659e5e3b7812580a1c/Podman/Interop/PMManager.m#L95).

2.  podman-macos successfully reads states from podman but fails to write.

    After you deal with locating the podman binary, you'll find podman-macos successfully reads information from podman.

    <img width="437" alt="스크린샷 2021-09-05 05 56 52" src="https://user-images.githubusercontent.com/4435445/132107866-9e269f50-e0ee-48fa-8206-f7d586984e73.png">

    But unfortunately any operation that tries to write something fails. For example, podman-macos is unable to stop podman VM.

    <img width="328" alt="스크린샷 2021-09-05 05 55 33" src="https://user-images.githubusercontent.com/4435445/132107843-8252134e-b026-49bd-a0f3-375c33b0b75a.png">

I'm wiling to fix these issues but I don't know how to build or debug this project. Is there any chance for us to cooperate with these issues?</div>

**Comment by heyvito** [comment]
Hi there, @sammcj! Let's continue this in #2, shall we? 🙌🏻
