### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by vraravam** [heyvito/podman-macos#4]
This is a great initiative. Could you please provide/host pre-built binaries via the GitHub releases? Having these hooked into `homebrew` could be a bonus.

**Comment by heyvito** [comment]
Hi there, @vraravam! You can find a built, signed, and notarized version on the [releases](https://github.com/heyvito/podman-macos/releases/) page. Just click the `podman.dmg` link there to download it. :)
Please let me know in case you run into any issues. :)

Cheers!
