### ISSUE TITLE
Support for catalina

### ISSUE THREAD

**Issue by MansM** [heyvito/podman-macos#6]
Because of the use of some legacy HW components we are still at catalina, support for macos catalina would be awesome

**Comment by heyvito** [comment]
Hi there, @MansM!
Good point. I'll try to adjust the deployment target and see what happens. 👍🏻

**Comment by heyvito** [comment]
@MansM Yesterday I uploaded a new release. When you can, could you kindly take a look? 🙌🏻

**Comment by karafior** [comment]
Release v1.1.0 does indeed work on Catalina.

The menu UX is not the same as other items on the status menus, but that should be a separate issue I believe.

**Comment by heyvito** [comment]
@karafior Would you mind opening a new issue describing the problem? (Would be awesome if you could attach some screenshots!)

Closing this one since it is confirmed to work on Catalina. :)
